<a href="https://colab.research.google.com/github/hannahTai/tibame-python/blob/main/python20260923_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import urllib.request as req
import bs4 as bs

def get_page(page_num):
    url = f"https://tabelog.com/tw/tokyo/rstLst/RC0123/{page_num}?SrtT=rt"
    print(url)
    resp = req.urlopen(url)
    content = resp.read()
    html = bs.BeautifulSoup(content)

    # html有沒有抓到完成的source
    ## 有 ok
    ## 沒有 加header

    # 建議抓完後續再處理

    rs = html.find_all("div", {"class":"list-rst__body"}) # 區塊

    table = []
    for r in rs:
        name = r.find("a", {"class": "list-rst__rst-name-target"}) # 超連結
        area_genre = r.find("div", {"class": "list-rst__area-genre"}) # 地點/種類
        rating = r.find("span", {"class": "c-rating__val"}) # 評價
        prices = r.find_all("span", {"class": "c-rating-v3__val"}) # 晚間價格+白天價格
        holiday = r.find("span", {"class": "list-rst__holiday-text"}) # 休假日
        name_text = name.get_text()
        name_href = name["href"]
        area_genre_text = area_genre.get_text().strip()
        rating_text = rating.get_text().strip()
        dinner_price_text = prices[0].get_text().strip()
        lunch_price_text = prices[1].get_text().strip()
        holiday_text = holiday.get_text().strip()

        row = {
            "rating":rating_text,
            "name":name_text,
            "url":name_href,
            "area_genre":area_genre_text,
            "lunch_price":lunch_price_text,
            "dinner_price":dinner_price_text,
            "holiday":holiday_text,
        }
        table.append(row)

    return table

https://tabelog.com/tw/tokyo/rstLst/RC0123/3?SrtT=rt

,rating,name,url,area_genre,lunch_price,dinner_price,holiday
0,3.64,關西風手打烏龍麵 Irasshai,https://tabelog.com/tw/tokyo/A1311/A131104/130...,入谷車站 275m / 烏龍麵,- JPY 999,- JPY 999,星期日
1,3.64,賞讃,https://tabelog.com/tw/tokyo/A1324/A132403/130...,京成立石車站 895m / 烏龍麵,- JPY 999,-,"星期日, 節假日"
2,3.64,Musashino Enza,https://tabelog.com/tw/tokyo/A1321/A132103/130...,石神井公園車站 935m / 烏龍麵,"JPY 1,000 - JPY 1,999",-,-
3,3.63,cuud,https://tabelog.com/tw/tokyo/A1315/A131504/131...,"羽田機場第1航廈車站 100m / 烏龍麵, 咖哩烏龍麵","JPY 1,000 - JPY 1,999","JPY 1,000 - JPY 1,999",-
4,3.63,稻庭烏龍麵與飯 金子半之助 Coredo室町店,https://tabelog.com/tw/tokyo/A1302/A130202/131...,"三越前車站 161m / 烏龍麵, 天婦羅蓋飯, 海鮮蓋飯","JPY 1,000 - JPY 1,999","JPY 1,000 - JPY 1,999",-
5,3.63,玉丁本店 八重洲店,https://tabelog.com/tw/tokyo/A1302/A130201/130...,"東京車站 215m / 烏龍麵, 郷土料理, 意式冰淇淋/冰淇淋","JPY 1,000 - JPY 1,999","JPY 1,000 - JPY 1,999",-
6,3.63,手打 Shimada,https://tabelog.com/tw/tokyo/A1306/A130602/130...,"表參道車站 147m / 烏龍麵, 蕎麥麵, 居酒屋 (酒館)","JPY 1,000 - JPY 1,999","JPY 4,000 - JPY 4,999",星期日
7,3.63,Daily Chico,https://tabelog.com/tw/tokyo/A1319/A131902/130...,"中野車站 383m / 軟冰淇淋, 烏龍麵, 站著吃蕎麥麵","JPY 1,000 - JPY 1,999","JPY 1,000 - JPY 1,999",-
8,3.63,小平烏龍麵 小平本店,https://tabelog.com/tw/tokyo/A1328/A132804/130...,一橋學園車站 1613m / 烏龍麵,- JPY 999,- JPY 999,-
9,3.63,雅樂,https://tabelog.com/tw/tokyo/A1309/A130905/130...,"飯田橋車站 156m / 烏龍麵, 居酒屋 (酒館)","JPY 1,000 - JPY 1,999","JPY 4,000 - JPY 4,999",星期日
10,3.63,烏龍麵攤五頭,https://tabelog.com/tw/tokyo/A1320/A132002/131...,"三鷹車站 509m / 烏龍麵, 居酒屋 (酒館)",- JPY 999,"JPY 2,000 - JPY 2,999",星期日
11,3.63,手打烏龍麵 福助,https://tabelog.com/tw/tokyo/A1328/A132804/131...,"青梅街道車站 412m / 烏龍麵, 日本酒酒吧",- JPY 999,-,"星期一, 星期二"
12,3.62,一滴八錢屋 新宿本店,https://tabelog.com/tw/tokyo/A1304/A130401/130...,"新宿車站 297m / 烏龍麵, 居酒屋 (酒館), 關東煮",- JPY 999,"JPY 4,000 - JPY 4,999",-
13,3.62,Oniyanma 中目黑店,https://tabelog.com/tw/tokyo/A1317/A131701/131...,中目黑車站 58m / 烏龍麵,- JPY 999,- JPY 999,-
14,3.62,TOKYO SUNFLOWER IIDABASHI,https://tabelog.com/tw/tokyo/A1309/A130905/132...,飯田橋車站 316m / 烏龍麵,- JPY 999,- JPY 999,-
15,3.62,正太郎烏龍麵,https://tabelog.com/tw/tokyo/A1321/A132105/130...,"上井草車站 518m / 烏龍麵, 咖哩烏龍麵",- JPY 999,- JPY 999,星期三
16,3.62,四ツ木製麵所,https://tabelog.com/tw/tokyo/A1324/A132403/131...,"京成立石車站 516m / 烏龍麵, 居酒屋 (酒館), 咖哩烏龍麵",- JPY 999,"JPY 2,000 - JPY 2,999","星期一, 星期二"
17,3.61,香川 一福 神田店,https://tabelog.com/tw/tokyo/A1310/A131002/131...,"小川町車站 347m / 烏龍麵, 天婦羅, 咖哩烏龍麵",- JPY 999,- JPY 999,-
18,3.61,烏龍麵店 新堀,https://tabelog.com/tw/tokyo/A1304/A130403/132...,代代木車站 133m / 烏龍麵,- JPY 999,"JPY 1,000 - JPY 1,999","星期一, 星期日"
19,3.61,Oniyanma 御茶之水店,https://tabelog.com/tw/tokyo/A1310/A131002/132...,御茶之水車站 73m / 烏龍麵,- JPY 999,- JPY 999,-

In [12]:
import pandas as pd

total = []
for i in range(10):
    page = i + 1
    partial_df = pd.DataFrame(get_page(page))
    total.append(partial_df)
df = pd.concat(total)
df

https://tabelog.com/tw/tokyo/rstLst/RC0123/1?SrtT=rt
https://tabelog.com/tw/tokyo/rstLst/RC0123/2?SrtT=rt
https://tabelog.com/tw/tokyo/rstLst/RC0123/3?SrtT=rt
https://tabelog.com/tw/tokyo/rstLst/RC0123/4?SrtT=rt
https://tabelog.com/tw/tokyo/rstLst/RC0123/5?SrtT=rt
https://tabelog.com/tw/tokyo/rstLst/RC0123/6?SrtT=rt
https://tabelog.com/tw/tokyo/rstLst/RC0123/7?SrtT=rt
https://tabelog.com/tw/tokyo/rstLst/RC0123/8?SrtT=rt
https://tabelog.com/tw/tokyo/rstLst/RC0123/9?SrtT=rt
https://tabelog.com/tw/tokyo/rstLst/RC0123/10?SrtT=rt

,rating,name,url,area_genre,lunch_price,dinner_price,holiday
0,3.84,村山 滿月烏龍麵,https://tabelog.com/tw/tokyo/A1329/A132901/130...,箱根崎車站 3321m / 烏龍麵,"JPY 1,000 - JPY 1,999","JPY 1,000 - JPY 1,999","星期一, 星期二"
1,3.83,麵匠 釜善,https://tabelog.com/tw/tokyo/A1310/A131002/132...,"淡路町車站 178m / 烏龍麵, 咖哩烏龍麵, 天婦羅",- JPY 999,- JPY 999,"星期日, 節假日"
2,3.81,烏龍麵 丸香,https://tabelog.com/tw/tokyo/A1310/A131003/130...,神保町車站 201m / 烏龍麵,- JPY 999,- JPY 999,"星期日, 節假日"
3,3.80,手打烏龍麵 Kogera,https://tabelog.com/tw/tokyo/A1328/A132805/131...,"小川車站 1250m / 烏龍麵, 天婦羅",- JPY 999,- JPY 999,"星期三, 星期四"
4,3.75,牛筋咖哩 小小的咖哩店,https://tabelog.com/tw/tokyo/A1304/A130404/130...,"大久保車站 167m / 咖喱, 咖哩烏龍麵",- JPY 999,-,"星期六, 星期日"
...,...,...,...,...,...,...,...
15,3.49,Kandaya 神田本店,https://tabelog.com/tw/tokyo/A1310/A131002/133...,神田車站 93m / 烏龍麵,- JPY 999,- JPY 999,-
16,3.49,肉讚岐 甚三烏龍麵 高田馬場店,https://tabelog.com/tw/tokyo/A1305/A130503/132...,"高田馬場車站 249m / 烏龍麵, 天婦羅, 便當","JPY 1,000 - JPY 1,999",-,"星期日, 節假日"
17,3.49,烏龍麵 居酒屋咲花善傳,https://tabelog.com/tw/tokyo/A1309/A130904/132...,"市谷車站 246m / 烏龍麵, 居酒屋 (酒館)",- JPY 999,"JPY 1,000 - JPY 1,999",星期日
18,3.48,CITYSHOP 東京站店,https://tabelog.com/tw/tokyo/A1302/A130201/132...,"東京車站 125m / 蔬菜料理, 三明治, 烏龍麵","JPY 1,000 - JPY 1,999","JPY 1,000 - JPY 1,999",-
19,3.48,Konakara 新丸大樓店,https://tabelog.com/tw/tokyo/A1302/A130201/130...,"東京車站 300m / 關東煮, 烏龍麵","JPY 1,000 - JPY 1,999","JPY 6,000 - JPY 7,999",-

- 前端(Local)
    - 修出回應(網頁)
        - HTML: 內容
        - CSS: 排版
        - JavaScript: 網頁動態
- 後端(Server)
    - 收網址
    - 程式處理網址(Flask,Django,FastAPI:Python)
        - 查詢資料庫
        - 讀取檔案
    - 把回應(html/json...)送回去

- CSS語法: 找到html區塊並加上排版
    - 找所有html名字
        ```
        a {
            backgroupd-color: red
        }
        ```
    - 為了區分要的區塊,會在html區塊加上特殊屬性class(class = "分類一 分類二")
        ```
        .分類名字 {
            backgroupd-color: red
        }
        ```
    - 如果要獨一無二的值,使用id (id="獨一無二的")
        ```
        #id名字 {
            backgroupd-color: red
        }
        ```

In [13]:
def add(n1, n2):
    n3 = n1 + n2
    return n3

b = add
b(3,5)

8

In [30]:
def func(n):
    return round(n*2, 1)

# apply(操作函式(不加小括號)), pandas 會一直處理
df["rating2"] = df["rating"].astype(float).apply(func)

df[["rating", "rating2"]]

   rating  rating2
0    3.84      7.7
1    3.83      7.7
2    3.81      7.6
3    3.80      7.6
4    3.75      7.5
..    ...      ...
15   3.49      7.0
16   3.49      7.0
17   3.49      7.0
18   3.48      7.0
19   3.48      7.0

[200 rows x 2 columns]

In [31]:
def func(s):
    s_spl = s.split(" / ")
    ans = {
        "area": "-",
        "genre": "-"
    }
    if len(s_spl) == 2:
        ans["area"] = s_spl[0]
        ans["genre"] = s_spl[1]
    elif len(s_spl) == 1:
        ans["genre"] = s_spl[0]
    return pd.Series(ans)

df[["area", "genre"]] = df["area_genre"].apply(func)
df

,rating,name,url,area_genre,lunch_price,dinner_price,holiday,rating2,area,genre
0,3.84,村山 滿月烏龍麵,https://tabelog.com/tw/tokyo/A1329/A132901/130...,箱根崎車站 3321m / 烏龍麵,"JPY 1,000 - JPY 1,999","JPY 1,000 - JPY 1,999","星期一, 星期二",7.7,箱根崎車站 3321m,烏龍麵
1,3.83,麵匠 釜善,https://tabelog.com/tw/tokyo/A1310/A131002/132...,"淡路町車站 178m / 烏龍麵, 咖哩烏龍麵, 天婦羅",- JPY 999,- JPY 999,"星期日, 節假日",7.7,淡路町車站 178m,"烏龍麵, 咖哩烏龍麵, 天婦羅"
2,3.81,烏龍麵 丸香,https://tabelog.com/tw/tokyo/A1310/A131003/130...,神保町車站 201m / 烏龍麵,- JPY 999,- JPY 999,"星期日, 節假日",7.6,神保町車站 201m,烏龍麵
3,3.80,手打烏龍麵 Kogera,https://tabelog.com/tw/tokyo/A1328/A132805/131...,"小川車站 1250m / 烏龍麵, 天婦羅",- JPY 999,- JPY 999,"星期三, 星期四",7.6,小川車站 1250m,"烏龍麵, 天婦羅"
4,3.75,牛筋咖哩 小小的咖哩店,https://tabelog.com/tw/tokyo/A1304/A130404/130...,"大久保車站 167m / 咖喱, 咖哩烏龍麵",- JPY 999,-,"星期六, 星期日",7.5,大久保車站 167m,"咖喱, 咖哩烏龍麵"
...,...,...,...,...,...,...,...,...,...,...
15,3.49,Kandaya 神田本店,https://tabelog.com/tw/tokyo/A1310/A131002/133...,神田車站 93m / 烏龍麵,- JPY 999,- JPY 999,-,7.0,神田車站 93m,烏龍麵
16,3.49,肉讚岐 甚三烏龍麵 高田馬場店,https://tabelog.com/tw/tokyo/A1305/A130503/132...,"高田馬場車站 249m / 烏龍麵, 天婦羅, 便當","JPY 1,000 - JPY 1,999",-,"星期日, 節假日",7.0,高田馬場車站 249m,"烏龍麵, 天婦羅, 便當"
17,3.49,烏龍麵 居酒屋咲花善傳,https://tabelog.com/tw/tokyo/A1309/A130904/132...,"市谷車站 246m / 烏龍麵, 居酒屋 (酒館)",- JPY 999,"JPY 1,000 - JPY 1,999",星期日,7.0,市谷車站 246m,"烏龍麵, 居酒屋 (酒館)"
18,3.48,CITYSHOP 東京站店,https://tabelog.com/tw/tokyo/A1302/A130201/132...,"東京車站 125m / 蔬菜料理, 三明治, 烏龍麵","JPY 1,000 - JPY 1,999","JPY 1,000 - JPY 1,999",-,7.0,東京車站 125m,"蔬菜料理, 三明治, 烏龍麵"
19,3.48,Konakara 新丸大樓店,https://tabelog.com/tw/tokyo/A1302/A130201/130...,"東京車站 300m / 關東煮, 烏龍麵","JPY 1,000 - JPY 1,999","JPY 6,000 - JPY 7,999",-,7.0,東京車站 300m,"關東煮, 烏龍麵"